# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_weather_darksky', '0002_weatherlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlocation',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
